### ISSUE TITLE
Maybe one more benefit

### ISSUE THREAD

**Issue by YushiOMOTE** [konoui/lipo#1]
> This is useful for environments such as CI/CD which does not provides macOS or [macOS lipo](https://ss64.com/osx/lipo.html)

macos github action has lipo but it is expensive: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

Thanks to this tool, we can still use cheaper Linux github actions 👍 Maybe we can mention that to the readme.

**Comment by konoui** [comment]
Thank you for your great feedback!
I will add it.
