### ISSUE TITLE
Can't overwrite file

### ISSUE THREAD

**Issue by JanisV** [konoui/lipo#6]
Original macOS lipo can overwrite input file when it is specified as output. But v0.2.3 can't overwrite file:

```
lipo -thin x86_64 my_file -output my_file
Error failed to write binary data: EOF
```

This feature used by pyInstaller.

**Comment by konoui** [comment]
Thank you for reporting the bug!
I will fix it.

**Comment by konoui** [comment]
@JanisV 
v0.3.0 has been released!

**Comment by JanisV** [comment]
Thank you!
