### ISSUE TITLE
Fat image creation fails to move file

### ISSUE THREAD

**Issue by gjasny** [konoui/lipo#7]
Hello,

if `TMPDIR` is on a different filesystem than the output file the operation fails:
```
root@d27ae656b029:/workspace# /go/bin/lipo -output foo -create foo.amd64 foo.arm64
Error rename /tmp/tmp-output-binary680144686 foo: invalid cross-device link
create:
  Create an universal binary(fat binary) from input thin binaries. 
  e.g. lipo path/to/binary.x86_64 path/to/binary.arm64e -create -output path/to/fat-binary
```

It's probably `os.Rename` that needs a fallback:
https://github.com/konoui/lipo/blob/5e7f85980dfa10d874d7e4584322a332c53bc874/pkg/lipo/thin.go#L65
https://github.com/konoui/lipo/blob/5e7f85980dfa10d874d7e4584322a332c53bc874/pkg/lipo/fat_arch.go#L43

Thanks,
Gregor

**Comment by konoui** [comment]
@gjasny 
v0.4.0 will work as it creates a temporary file in same directory of output file.
