### ISSUE TITLE
Reproducability?

### ISSUE THREAD

**Issue by quite** [konoui/lipo#8]
Is the output of lipo reproducible? I.e. will the same input always generate the exact same output?

**Comment by quite** [comment]
And in particular, doesn't embed anything environment or time specific. Reading up a little on the fat binary spec, it seems this is the case.

**Comment by konoui** [comment]
Is your question related to the fat binary specification?
When using the lipo tool, it appends the original binaries and a fat header to create an output file. 
From my experience, lipo tool does not inject any environment or time-specific values. 
However, I did encounter an edge case (https://github.com/konoui/lipo/issues/4) when using the '-fat64' flag, which is not commonly used. 
In this case, the hashed value of fat binary differed under execution environments.

**Comment by quite** [comment]
Yes, the spec and the lipo tool. It looks good, except for what you pointed at now.

So, if I understood correctly, Apple's lipo tool ends up not being really reproducible if the fat_arch_64 type of fat-binary is used. Because a random value ends up in the fat_arch_64's reserved field, because they allocate the struct on the stack and forgot to zero it.

**Comment by konoui** [comment]
Yes, my lipo will have reproducibility because Go initializes these values to zero.
